### ISSUE TITLE
Side effects of AGPL license

### ISSUE THREAD

**Issue by sprice** [Rari-Capital/solmate#103]
Discussions aren't enabled so I'm asking this as an issue.

Given this project is AGPL does that mean that any on-chain artwork is automatically required to be licensed AGPL as well?

Are there any other side-effects developers and/or artists should be aware of?

Here's a recent [Twitter Discussion](https://twitter.com/wattsyart/status/1477797370972803073) on this topic.

**Comment by sprice** [comment]
If on-chain artwork must also be licensed AGPL, this seems like an important item to notify users of.

@transmissions11 do you have any feedback for us?

**Comment by transmissions11** [comment]
im not a lawyer, i wont make any comments here

**Comment by sprice** [comment]
@transmissions11 First of all thanks so much for this project. It's quite impressive how much of an improvement it is on the OZ work in terms of gas savings.

> im not a lawyer, i wont make any comments here

no worries. I can ask some questions that don't need to be answered by a lawyer 😄 

Please don't read too much directness or curtness into this... Simply trying to craft some simple questions to learn more about the intention of the project 😊 

How was the AGPL license chosen?

Is it your desire that any on chain art be required to be licensed with the AGPL?

Who controls the license of this project?

Thanks so much!

**Comment by Vypo** [comment]
I am not a lawyer, but art linked to by an AGPL contract would be a separate work from the contract itself, and so could be licensed separately.

These two questions from the GPL FAQ go over this pretty well:

 - [Is there some way that I can GPL the output people get from use of my program?](https://www.gnu.org/licenses/gpl-faq.html#GPLOutput)
 - [In what cases is the output of a GPL program covered by the GPL too?](https://www.gnu.org/licenses/gpl-faq.html#WhatCaseIsOutputGPL)

**Comment by cxkoda** [comment]
yes, but this would no longer be the case for in-chain projects, where the art is generated on-the-fly by linked contracts. in this case also the generative algorithm needs to be made AGPL from my understanding, which might not be desirable in many cases.
