### ISSUE TITLE
include interfaces

### ISSUE THREAD

**Issue by wschwab** [Rari-Capital/solmate#104]
Hi!

I'd like to encourage Solmate to include interfaces for ERC20, 721, and 1155. This is especially helpful when building contracts that need to interact with these standards. There may be a rationale that you'd prefer people to custom-make interfaces that include only the specific functions they're consuming (probably don't need `name()` from 20 or 721 in there, for example), but I'd argue that having interfaces there makes the library as a whole more versatile and useful.

I'd be happy to contribute this myself, if you're interested in having it - it's obviously not that much work.

**Comment by transmissions11** [comment]
we use contracts as interfaces, dont plan to change that
