### ISSUE TITLE
Make EIP712 functionality compatible with delegate calls

### ISSUE THREAD

**Issue by k06a** [Rari-Capital/solmate#130]
Consider borrowing the idea from this PR: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2852

You have to cache the address of the smart contract in immutable to prevent issues when implementation is used via delegate calls.

**Comment by transmissions11** [comment]
would prefer ppl fork, don't want to increase complexity for a use case we don't encourage

**Comment by k06a** [comment]
@transmissions11 someone could use your library in this manner and get suffered from this issue. I assume the fix is relatively cheap, just cache address of `this` in immutable.

**Comment by transmissions11** [comment]
There are plenty of other foot guns, such as the reentrancy guard not being compatible with delegatecall
