### ISSUE TITLE
Incompatible importing system between Foundry/DappTools and Hardhat

### ISSUE THREAD

**Issue by xMasashi** [Rari-Capital/solmate#136]
Using Foundry: `import {ERC20} from "@solmate/src/tokens/ERC20.sol"`.   

Using Hardhat: `import {ERC20} from "@rari-capital/solmate/src/tokens/ERC20.sol"`.   

Keeping consistency among frameworks would be better for those who need/want to use both of them.

**Comment by xMasashi** [comment]
I'm aware that you can use remappings to fix this issue, but would be nice to have this consistency by default.

for those who need help with that, on your `remappings.txt` file you can add this line:   
`@rari-capital/solmate/=lib/solmate/`.

**Comment by transmissions11** [comment]
what? this has nothing to do with us.
