### ISSUE TITLE
Update ERC4626 Interface

### ISSUE THREAD

**Issue by Joeysantoro** [Rari-Capital/solmate#142]
https://github.com/Rari-Capital/solmate/blob/7f433c79c498f7cef10e1144e617f3359d19a4b4/src/mixins/ERC4626.sol#L123

`assetsOf` and `assetsPerShare` are no longer in the interface (now in last call)

these should be changed to `convertToShares` and `convertToAssets`

**Comment by transmissions11** [comment]
👍
