### ISSUE TITLE
Permit implementation on ERC721 improvement

### ISSUE THREAD

**Issue by dievardump** [Rari-Capital/solmate#16]
https://github.com/Rari-Capital/solmate/blob/3fb504ac72be84a7f090ebd047a61c2f3a3043df/src/erc721/ERC721.sol#L180

For NFTs, the nonce should probably be more `mapping(uint256 => uint256)` because it's for a tokenId.

Your implementation will invalidate any permit on any other id of this owner, once a permit is used.

Whenever we should here invalidate any other permit on this tokenId, not from this owner.

**Comment by transmissions11** [comment]
Please comment these on the relevant PR— it has not been merged yet.
