### ISSUE TITLE
ERC20 Abstract - why?

### ISSUE THREAD

**Issue by PatrickAlphaC** [Rari-Capital/solmate#160]
https://github.com/Rari-Capital/solmate/blob/main/src/tokens/ERC20.sol

I can't figure out why this contract is `abstract`. Am I missing something?

**Comment by transmissions11** [comment]
because you need to inherit it and expose some sort of public mint or burn (or at least do in the constructor), otherwise there will never be any tokens in circulation

**Comment by PatrickAlphaC** [comment]
Ahh I see. Thanks!
