### ISSUE TITLE
About licence for SafeTransferLib codes

### ISSUE THREAD

**Issue by ayanamidev** [Rari-Capital/solmate#163]
Wouldn't be good to preserve `LGPL-3.0-or-later` since the codes were derived from Gnosis Protocol V2 contracts?

https://twitter.com/transmissions11/status/1463570029413236737

https://github.com/Rari-Capital/solmate/blob/main/src/utils/SafeTransferLib.sol#L32

Original Source: https://github.com/gnosis/gp-v2-contracts/blame/main/src/contracts/libraries/GPv2SafeERC20.sol#L9

Also, I think the reference to original source code is missing as well.

**Comment by 0xAyanami** [comment]
Conditions of LGPL-3.0-or-later license: Disclose source & Preserving original license

https://github.com/gnosis/gp-v2-contracts/blob/main/LICENSE

https://github.com/gnosis/gp-v2-contracts/blame/main/src/contracts/libraries/GPv2SafeERC20.sol#L1

**Comment by 0xAyanami** [comment]
![4h8kf83](https://user-images.githubusercontent.com/91770832/158791363-49935a30-1542-4dde-b661-642ca8e538e7.jpeg)

https://twitter.com/transmissions11/status/1504259113622007809

_But ser how did you know about me_

**Comment by transmissions11** [comment]
have talked with counsel about this extensively, solmate STL no longer bears any resemblance to gnosis' work, it was rewritten as part of the PR where the attribution was removed.
