### ISSUE TITLE
add ERC1155 logic for SafeTransferLib

### ISSUE THREAD

**Issue by z0r0z** [Rari-Capital/solmate#186]
currently, `safeTransferFrom` though designed for ERC20 handling, will work with an ERC721 `transferFrom` and null-data `safeTransferFrom` by inputting `id` into the `amount` param. To extend this library, though, we might add something to handle `safeTransferFrom` for ERC1155 tokens, which has [extra params ](https://github.com/Rari-Capital/solmate/blob/main/src/tokens/ERC1155.sol#L55) for `id` and `data`.

**Comment by transmissions11** [comment]
1155s are generally pretty compliant? dont rly see the need
