### ISSUE TITLE
add Clone/Init variants for Tokens

### ISSUE THREAD

**Issue by z0r0z** [Rari-Capital/solmate#187]
currently, when I want to create cheap factories to spin up solmate assets, I have to redo the contracts, which isn't super comfy

this should prolly also pair with an example factory implementation based on https://github.com/wighawag/clones-with-immutable-args

**Comment by transmissions11** [comment]
not ready to support clones yet, but long term may reopen

**Comment by z0r0z** [comment]
sounds good. Here's a good example of a clone solmate erc20 https://github.com/ZeframLou/vested-erc20/blob/main/src/lib/ERC20.sol
