### ISSUE TITLE
NPM package out of date

### ISSUE THREAD

**Issue by rayquaza7** [Rari-Capital/solmate#223]
1. `forge install https://github.com/Rari-Capital/solmate`, give u the following function defs for supportsInterface():
ERC1155: `function supportsInterface(bytes4 interfaceId) public view virtual returns (bool)`
ERC721: `function supportsInterface(bytes4 interfaceId) public view virtual returns (bool)`

2. `npm install @rari-capital/solmate` gives ya:
ERC721: `function supportsInterface(bytes4 interfaceId) public pure virtual returns (bool) `
ERC1155: `function supportsInterface(bytes4 interfaceId) public pure virtual returns (bool)`

the function state mutability changes from view to pure in the NPM package. 

[I can see that there was commit that changed this, so I'd assume the npm package is out of date](https://github.com/Rari-Capital/solmate/commit/0a121c54b23ccde77bb0dd84a59b71783c126894)

**Comment by transmissions11** [comment]
ik— next release will be v7
