### ISSUE TITLE
token interfaces

### ISSUE THREAD

**Issue by z0r0z** [Rari-Capital/solmate#230]
IERC ... 20, 721, 1155

**Comment by transmissions11** [comment]
dont like interfaces, just use the contract

**Comment by mds1** [comment]
But then the whole contract shows up on Etherscan / in a flattened version, when really you're just using an interface, making it harder to read cause there's a bunch of unused code 😅

**Comment by transmissions11** [comment]
lol i hate being a position of power against friends who i disagree with, feels so dirty

but my honest thoughts are: 
- thats not really worth optimizing for
- if it is something you care about, use multi file verification
