### ISSUE TITLE
🔍 Look at use of bitshifts and if they can be optimized post 0.8

### ISSUE THREAD

**Issue by transmissions11** [Rari-Capital/solmate#5]
- Are there new operators to do things cheaply?
- Do we make things unchecked?

**Comment by rajivpo** [comment]
![image](https://user-images.githubusercontent.com/19913716/133025835-ccadc29a-fdb6-4d7d-bdd1-b66794a68f97.png)

from here: https://docs.soliditylang.org/en/v0.8.7/control-structures.html#unchecked

**Comment by transmissions11** [comment]
@rajivpo Does that apply to stuff like `&`/`|`/`~`?

**Comment by transmissions11** [comment]
We also do exponentiation here which I think can be unchecked: https://github.com/Rari-Capital/solmate/blob/370f014278419d6d11687decfa9d2b30d173d4c3/src/auth/authorities/RolesAuthority.sol#L89

**Comment by rajivpo** [comment]
I think this does apply but would wanna double check to be sure.

**Comment by rajivpo** [comment]
Pretty small savings
![image](https://user-images.githubusercontent.com/19913716/133194735-be193f69-45a6-423a-8e97-cdb35c033f0b.png)

the tests in question are 

```solidity
function testUserHasRole() public {
        uint8 rootRole = 0;
        roles.setUserRole(self, rootRole, true);
        assertTrue(roles.doesUserHaveRole(self, rootRole));
    }
function testUserHasRoleUnchecked() public {
        uint8 rootRole = 0;
        roles.setUserRole(self, rootRole, true);
        assertTrue(roles.doesUserHaveRoleUnchecked(self, rootRole));
    }
```
where `doesUserHaveRoleUnchecked` is 
```solidity
function doesUserHaveRoleUnchecked(address who, uint8 role) external view returns (bool) {
        bytes32 roles = getUserRoles(who);
        unchecked {
            bytes32 shifted = bytes32(uint256(uint256(2)**uint256(role)));
            return bytes32(0) != roles & shifted;
        }
    }
```

**Comment by transmissions11** [comment]
all coming from exponentiation probably?
