### ISSUE TITLE
✂️ Snip ERC20 import in SafeTransferLib

### ISSUE THREAD

**Issue by z0r0z** [Rari-Capital/solmate#55]
The typical use of `SafeTransferLib` will involve a contract that handles external tokens.

Currently Solmate includes `ERC20` token as import and aliases addresses as ERC20. Therefore, using this library will involve deploying a token.

Wouldn't it be simpler to snip?

**Comment by transmissions11** [comment]
I use ERC20 as an interface, not necessarily as a concretely deployed solmate token, tho i get that's not everyone's style (i just think IERC20 is dumb 🤷‍♂️)

**Comment by transmissions11** [comment]
gonna close if you don't mind, feel free to reopen :)

**Comment by z0r0z** [comment]
all gucci. response makes sense
