### ISSUE TITLE
✨ ERC1155

### ISSUE THREAD

**Issue by transmissions11** [Rari-Capital/solmate#7]

**Comment by platocrat** [comment]
![image](https://user-images.githubusercontent.com/37757724/133097948-d158d640-a1c5-4e84-8a02-0ee858575bd2.png)

**Comment by andy8052** [comment]
is this a WIP or do you want/need someone to step in and do this?

**Comment by transmissions11** [comment]
@andy8052 Would love someone to step in. I think Plato got caught up in some personal stuff 👍

**Comment by transmissions11** [comment]
closing issues for things that have prs uwu
