### ISSUE TITLE
[Bug] Please check bool success when making low level calls/staticcall

### ISSUE THREAD

**Issue by Amxx** [Rari-Capital/solmate#82]
In ERC721, the [`safeTransferFrom`](https://github.com/Rari-Capital/solmate/blob/audit-fixes/src/tokens/ERC721.sol#L159-L176) function checks that the receiver, if it contains code (i.e. is a live smart contracts) by doing so 

```
if (to.code.length > 0) {
    // selector = "onERC721Received(address,address,uint256,bytes)".
    (, bytes memory returned) = to.staticcall(abi.encodeWithSelector(0x150b7a02,
        msg.sender, from, tokenId, data));
            
    bytes4 selector = abi.decode(returned, (bytes4));
            
    require(selector == 0x150b7a02, 'NOT_ERC721_RECEIVER');
}
```

The only reason I can see for not doing 
```
 (bool success, bytes memory returned) = to.staticcall(abi.encodeWithSelector(0x150b7a02,
        msg.sender, from, tokenId, data));  
...
require(success && selector == 0x150b7a02, 'NOT_ERC721_RECEIVER');
```
is to save some gas. 

Adding the extra check is really not that expensive ... but what does removing it do? It considers a "valid" situation where the receiver would revert with a revert data that starts with `0x150b7a02`. Since 0.8.4, custom errors make this situation not very unlikely.

While the danger is limited, it is a clear difference between your code and the ERC721 expected behavior.

**Comment by transmissions11** [comment]
yup good catch, agreed thats not a safe impl. the NFT impls in `audit-fixes` are not production ready and have not been audited (or even looked at in depth by me yet hehe)— but will make sure to correct before merging into our v6 release!

**Comment by transmissions11** [comment]
fixed, thx again!
