### ISSUE TITLE
Add ERC-20 error messages

### ISSUE THREAD

**Issue by CodeSandwich** [Rari-Capital/solmate#90]
Currently many common ERC-20 user errors, like insufficient balance or unapproved transfer are detected implicitly by Solidity's checked arithmetic. While it's sound, it only emits generic overflow errors, it doesn't say what's wrong. An oldschool unchecked math and explicit overflow detection with meaningful error messages could be the solution.

**Comment by transmissions11** [comment]
this is intentional. feel free to fork if you prefer string error messages for everything

**Comment by CodeSandwich** [comment]
> this is intentional

Interesting, why? Is it to cut gas when deploying the contract and when building an error to return?

**Comment by transmissions11** [comment]
keeps the code clean and cuts down on bytecode size yeah

we're not the first ones to do this fwiw, its done in the [original uniswapv2 erc20](https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2ERC20.sol), and [recommended in audits like ChainSecurity's cToken review](https://chainsecurity.com/wp-content/uploads/2021/12/ChainSecurity_Compound_cToken_smart-contract-audit_Nov-26th-2021.pdf)
