### ISSUE TITLE
Define storage as private to mitigate inherited contracts to do stupid things

### ISSUE THREAD

**Issue by yaronvel** [Rari-Capital/solmate#91]
Take [ERC20](https://github.com/Rari-Capital/solmate/blob/main/src/tokens/ERC20.sol) as an example.
There is an implicit assumption that `totalSupply` is modified only via `_mint` and `_burn`.
However, the storage is defined as `public`, and thus a contract that inherits it can modified it. And in this case it is no longer sound to do uncecked arithmetic e.g., [here](https://github.com/Rari-Capital/solmate/blob/main/src/tokens/ERC20.sol#L178).

One would argue that someone would have to work really hard (or to be really stupid) to break it, however if this is intended to be a base layer for many future projects, and given how stupid some people in the ecosystem are, and given there is a relatively easy solution to mitigate it, I think the code will benefit from making `totalSupply` and `balanceOf` as private storage variables, which will prevent a contract that inherits it from accessing the variable (this is a compiler verification that is done in solc 8).

**Comment by transmissions11** [comment]
appreciate the issue, but it is solmate's philosophy to give developer's flexibility at the cost of allowing them to shoot themselves in the foot if they desire

if we truly wanted this library to be footgun free there are a lot more changes we would need to make beyond privating these state variables. 

i'd encourage new developers to use a footgun free library like OpenZeppelin, and only consider incorporating solmate if they're confident with the language and have read through the files they use top to bottom

**Comment by transmissions11** [comment]
to emphasize this point, i have added a safety warning above the installation section of the readme:

<img width="655" alt="Screen Shot 2022-01-02 at 12 32 08 PM" src="https://user-images.githubusercontent.com/26209401/147888727-3dffd087-20a1-4964-a4bd-dbb3872b5f4e.png">
