### ISSUE TITLE
Can mint burnt tokens

### ISSUE THREAD

**Issue by nemani** [Rari-Capital/solmate#92]
https://github.com/Rari-Capital/solmate/blob/14db7f908d0b344f12d409b1e21339024c4466ee/src/tokens/ERC721.sol#L163

not sure if this is by design but there doesn’t seem to be anything stopping someone from minting a burnt token.

A solution might be to use some other burn address instead of 0 like DEADBEEF.

**Comment by transmissions11** [comment]
i mean yeah OZ's does too?

**Comment by transmissions11** [comment]
if you want to expose a public burn as is and mint as well, but dont want double minting you should add another mapping like  `minted`
